Repository Team-MovieToGather/MovieToGather, pull requests merged in 2024-03, with the labels that each got.

#12 Feat/#1 구글 로그인 기능 구현
  build.gradle.kts
  src/main/kotlin/org/spartaa3/movietogather/domain/member/controller/MemberController.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/member/dto/LoginResponse.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/member/entity/Member.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/member/repository/MemberRepository.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/member/service/CustomMemberDetailService.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/member/service/MemberService.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/review/repository/ReviewRepository.kt
  src/main/kotlin/org/spartaa3/movietogather/infra/Security/SecurityConfig.kt
  src/main/kotlin/org/spartaa3/movietogather/infra/Security/jwt/CustomAuthenticationEntryPoint.kt
  src/main/kotlin/org/spartaa3/movietogather/infra/Security/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/org/spartaa3/movietogather/infra/Security/jwt/JwtAuthenticationToken.kt
  src/main/kotlin/org/spartaa3/movietogather/infra/Security/jwt/JwtPlugin.kt
  src/main/kotlin/org/spartaa3/movietogather/infra/Security/jwt/UserPrincipal.kt
  src/main/kotlin/org/spartaa3/movietogather/infra/swagger/SwaggerConfig.kt
Labels: enhancement

#19 Feat: CI 기능 추가
  .github/workflows/Integration.yml
  .gitignore
  build.gradle.kts
  src/main/resources/application.yml
  src/test/kotlin/org/spartaa3/movietogather/domain/review/MovieToGatherApplicationTests.kt
  src/test/kotlin/org/spartaa3/movietogather/domain/review/controller/ReviewControllerTest.kt
  src/test/kotlin/org/spartaa3/movietogather/domain/review/service/ReviewServiceImplTest.kt
Labels: enhancement

#31 Feat: 영화 검색 기능 추가
  src/main/kotlin/org/spartaa3/movietogather/domain/api/service/ApiService.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/api/service/TmdbApiService.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/api/service/TmdbApiServiceImpl.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/review/controller/ReviewController.kt
  src/main/kotlin/org/spartaa3/movietogather/infra/api/ApiProperties.kt
  src/main/resources/application.yml
Labels: enhancement

#34 Feat : CD 기능 추가
  .github/workflows/deploy.yml
  .github/workflows/integration.yml
  Dockerfile
  build.gradle.kts
  docker-compose.yml
  src/main/kotlin/org/spartaa3/movietogather/infra/security/SecurityConfig.kt
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/test/kotlin/org/spartaa3/movietogather/domain/review/MovieToGatherApplicationTests.kt
  src/test/kotlin/org/spartaa3/movietogather/domain/review/controller/ReviewControllerTest.kt
  src/test/kotlin/org/spartaa3/movietogather/domain/review/repository/ReviewQueryRepositoryImplTest.kt
  src/test/kotlin/org/spartaa3/movietogather/domain/review/repository/ReviewRepositoryImplTest.kt
  src/test/kotlin/org/spartaa3/movietogather/domain/review/service/ReviewServiceImplTest.kt
Labels: enhancement

#45 Bugfix : 영화이미지 Null 버그 수정
  src/main/kotlin/org/spartaa3/movietogather/domain/api/service/ApiService.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/api/service/TmdbApiService.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/api/service/dto/response/MovieResponse.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/comments/repository/CommentsRepository.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/comments/service/CommentsServiceImpl.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/review/controller/ReviewController.kt
  src/main/kotlin/org/spartaa3/movietogather/global/exception/dto/BaseResponseCode.kt
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: bug

#47 Feat : CD
  .github/workflows/deploy.yml
  .github/workflows/integration.yml
  Dockerfile
  build.gradle.kts
  docker-compose.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/kotlin/org/spartaa3/movietogather/MovieToGatherApplicationTests.kt
Labels: bug

#52 Refactor : 프론트 데이터 구현 리팩토링
  build.gradle.kts
  src/main/kotlin/org/spartaa3/movietogather/domain/api/service/TmdbApiService.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/api/service/dto/response/MovieResponse.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/comments/controller/CommentsController.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/review/controller/ReviewController.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/review/dto/ReviewRequest.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/review/service/ReviewServiceImpl.kt
  src/main/kotlin/org/spartaa3/movietogather/infra/security/SecurityConfig.kt
Labels: refactor

#58 Feat : 영화 검색 캐싱 기능 추가
  src/main/kotlin/org/spartaa3/movietogather/MovieToGatherApplication.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/api/service/TmdbApiService.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/api/service/dto/response/MovieResponse.kt
  src/main/kotlin/org/spartaa3/movietogather/infra/redis/RedisConfig.kt
Labels: enhancement

#63 Refactor : 별점 삭제
  .github/workflows/deploy.yml
  build.gradle.kts
  docker-compose.yml
  src/main/kotlin/org/spartaa3/movietogather/domain/review/dto/ReviewRequest.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/review/dto/ReviewResponse.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/review/entity/Review.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/review/service/ReviewServiceImpl.kt
  src/main/kotlin/org/spartaa3/movietogather/infra/cors/CorsConfig.kt
  src/main/kotlin/org/spartaa3/movietogather/infra/security/SecurityConfig.kt
  src/main/resources/application-prod.yml
  src/test/kotlin/org/spartaa3/movietogather/domain/review/controller/ReviewControllerTest.kt
  src/test/kotlin/org/spartaa3/movietogather/domain/review/entity/ReviewTest.kt
  src/test/kotlin/org/spartaa3/movietogather/domain/review/repository/ReviewRepositoryImplTest.kt
  src/test/kotlin/org/spartaa3/movietogather/domain/review/service/ReviewServiceImplTest.kt
Labels: refactor

#68 Refactor : 리뷰&댓글 사용자 정보
  .github/workflows/deploy.yml
  src/main/kotlin/org/spartaa3/movietogather/domain/comments/controller/CommentsController.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/comments/entity/Comments.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/comments/service/CommentsService.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/comments/service/CommentsServiceImpl.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/review/controller/ReviewController.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/review/entity/Review.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/review/service/ReviewService.kt
  src/main/kotlin/org/spartaa3/movietogather/domain/review/service/ReviewServiceImpl.kt
  src/test/kotlin/org/spartaa3/movietogather/domain/review/controller/ReviewControllerTest.kt
  src/test/kotlin/org/spartaa3/movietogather/domain/review/entity/ReviewTest.kt
  src/test/kotlin/org/spartaa3/movietogather/domain/review/repository/ReviewRepositoryImplTest.kt
  src/test/kotlin/org/spartaa3/movietogather/domain/review/service/ReviewServiceImplTest.kt
Labels: refactor
